name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 Gitleaks (secrets)
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --no-git --redact

      # 🔐 SAST (Semgrep)
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config auto

      # 🐘 Setup PHP (obligatoire pour Symfony)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      # 🔐 Dependencies audit (Symfony fix)
      - name: Composer install + audit
        run: |
          cd project
          echo "APP_ENV=prod" > .env
          echo "APP_SECRET=dummy" >> .env
          composer install --no-interaction --no-progress --no-scripts --ignore-platform-req=ext-redis
          composer audit || true

      # 🔥 SonarCloud (qualité + sécurité)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=khayemzribi8-ctrl_e-commerce-app
            -Dsonar.organization=khayemzribi8-ctrl
            -Dsonar.sources=project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 🐳 Build Docker image
      - name: Build Docker image
        run: docker build -t symfony-app:latest ./project

      # 🔐 Trivy scan
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: symfony-app:latest
          severity: HIGH,CRITICAL
          exit-code: 0

      # 🚨 OWASP ZAP (DAST)
      - name: Run OWASP ZAP scan
        run: |
          docker run --rm -t \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t ${{ secrets.NGROK_URL }} \
            -r zap-report.html || true

      # 📦 Upload ZAP report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
