name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          args: detect --source=. --no-git
      # 🔐 Secrets scanning
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # 🔐 SAST (code analysis)
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config auto

      # 🔐 Dependencies audit (PHP)
      - name: Composer audit
        run: |
          cd project
          composer install --no-interaction --no-progress
          composer audit || true

      # 🐳 Build Docker image
      - name: Build Docker image
        run: docker build -t symfony-app:latest ./project

      # 🔐 Scan Docker image (Trivy FIXED)
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: symfony-app:latest
          severity: HIGH,CRITICAL
          exit-code: 0   # 🔥 ne bloque pas la pipeline
